### ISSUE TITLE
Prepare for release

### ISSUE THREAD

**Issue by vpinchaudhary** [vpinchaudhary/TradeTrove#10]
- [ ] Compile a release build of the mod.
- [ ] Write a user-friendly README for your GitHub repository, including installation instructions, features list, and any known issues.
- [ ] Publish to mod distribution platforms like CurseForge.
