### ISSUE TITLE
Implement a trading center block or entity

### ISSUE THREAD

**Issue by vpinchaudhary** [vpinchaudhary/TradeTrove#4]
- [ ] Design the trading center's UI.
- [ ] Allow players to sell items for coins based on the price list.
- [ ] Allow players to buy items using coins.
