### ISSUE TITLE
Implement player-created shops.

### ISSUE THREAD

**Issue by vpinchaudhary** [vpinchaudhary/TradeTrove#6]
- [ ] Allow players to define their own selling price for items.
- [ ] Implement a UI for shop creation and management.
- [ ] Allow other players to purchase from these player-created shops.
